{
  "parameters": [
    { "name": "thickness", "value": 19, "unit": "mm" },
    { "name": "back_thickness", "value": 5, "unit": "mm" },
    { "name": "x", "value": 0, "unit": "mm" },
    { "name": "y", "value": 0, "unit": "mm" },
    { "name": "z", "value": 0, "unit": "mm" },
    { "name": "cabinet_height", "value": 800, "unit": "mm" },
    { "name": "cabinet_width", "value": 500, "unit": "mm" },
    { "name": "cabinet_depth", "value": 600, "unit": "mm" }
  ],
  "geometries": {
    "A": {
      "geometry": "Box",
      "args": ["${cabinet_depth}", "${cabinet_width}", "${thickness}"]
    },
    "B": {
      "geometry": "Box",
      "args": ["${cabinet_height}", "${cabinet_depth}", "${thickness}"]
    },
    "C": {
      "geometry": "Box",
      "args": ["${cabinet_height}", "${cabinet_width} - (2* ${thickness})", "${back_thickness}"]
    },
    "D": {
      "geometry": "Line",
      "args": [
        ["${x} + (${cabinet_width}/2) + 50", "${y}", "${z}"],
        ["${x} + (${cabinet_width}/2) + 50", "${cabinet_height}", 0]
      ]
    }
  },
  "assembly": {
    "name": "cabinet1",
    "parts": [
      {
        "id": "unterboden",
        "geometryReference": "A",
        "position": ["${x}", "${y}", "${z}"],
        "rotation": [90, 0, 90]
      },
      {
        "id": "oberboden",
        "geometryReference": "A",
        "position": ["${x}", "${y} + ${cabinet_height} + ${thickness}", "${z}"],
        "rotation": [90, 0, 90]
      },
      {
        "id": "seite_links",
        "geometryReference": "B",
        "position": ["${x} - (${cabinet_width} /2) + (${thickness} /2)", "${y} + (${cabinet_height} /2) + (${thickness} /2)", "${z}"],
        "rotation": [0, 90, 90]
      },
      {
        "id": "seite_rechts",
        "geometryReference": "B",
        "position": ["${x} + (${cabinet_width} /2) - (${thickness} /2)", "${y} + (${cabinet_height} /2) + (${thickness} /2)", "${z}"],
        "rotation": [0, 90, 90]
      },
      {
        "id": "r√ºckwand",
        "geometryReference": "C",
        "position": ["${x}", "${y} + (${cabinet_height} /2) + (${thickness} /2)", "${z} - (${cabinet_depth}/2) + (${back_thickness} /2) "],
        "rotation": [0, 0, 90]
      },
      {
        "id": "test",
        "geometryReference": "D",
        "position": [0, 0, 0],
        "rotation": [0, 0, 0]
      }
    ]


  }
}
